import type { GlobalThemeOverrides } from 'naive-ui'

export const vercelThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#171717',
    primaryColorHover: '#333333',
    primaryColorPressed: '#000000',
    primaryColorSuppl: '#171717',
    bodyColor: '#fafafa',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    tableColor: '#ffffff',
    inputColor: '#ffffff',
    textColorBase: '#171717',
    textColor1: '#171717',
    textColor2: '#4d4d4d',
    textColor3: '#888888',
    borderColor: '#ebebeb',
    dividerColor: '#ebebeb',
    actionColor: '#fafafa',
    clearColor: '#ebebeb',
    hoverColor: '#f5f5f5',
    // Semantic
    successColor: '#0070f3',
    warningColor: '#f5a623',
    errorColor: '#ee0000',
    infoColor: '#0070f3',
    // Border radius
    borderRadius: '6px',
    borderRadiusSmall: '4px',
    // Font
    fontFamily: 'Inter, system-ui, -apple-system, sans-serif',
    fontFamilyMono: '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, monospace',
    fontWeightStrong: '600',
  },
  Button: {
    textColorPrimary: '#ffffff',
    colorPrimary: '#171717',
    colorHoverPrimary: '#333333',
    colorPressedPrimary: '#000000',
    borderPrimary: '1px solid #171717',
    borderRadius: '100px',
    borderRadiusSmall: '100px',
    fontWeight: '500',
    fontSize: '14px',
    fontSizeSmall: '14px',
    height: '40px',
    heightSmall: '32px',
    // Secondary (tertiary) ghost
    textColorTertiary: '#171717',
    borderTertiary: '1px solid #ebebeb',
    colorHoverTertiary: '#fafafa',
  },
  Card: {
    color: '#ffffff',
    borderColor: '#ebebeb',
    borderRadius: '8px',
    paddingMedium: '24px',
    paddingSmall: '16px',
    paddingHuge: '32px',
    titleTextColor: '#171717',
    titleFontWeight: '600',
    actionColor: '#ffffff',
  },
  Input: {
    color: '#ffffff',
    borderColor: '#ebebeb',
    borderHoverColor: '#a1a1a1',
    borderFocusColor: '#171717',
    borderRadius: '6px',
    height: '40px',
    textColor: '#171717',
    placeholderColor: '#888888',
    fontSize: '14px',
  },
  Tag: {
    borderRadius: '100px',
    fontSize: '12px',
    fontWeight: '400',
    colorSuccess: '#fafafa',
    textColorSuccess: '#171717',
    borderSuccess: '1px solid #171717',
    colorWarning: '#ffefcf',
    textColorWarning: '#ab570a',
    colorInfo: '#fafafa',
    textColorInfo: '#4d4d4d',
    borderInfo: '1px solid #ebebeb',
  },
  Menu: {
    itemTextColor: '#4d4d4d',
    itemTextColorHover: '#171717',
    itemTextColorActive: '#171717',
    itemColorActive: '#f5f5f5',
    itemColorActiveHover: '#f5f5f5',
    itemHeight: '36px',
    borderRadius: '100px',
    fontWeight: '400',
    fontSize: '14px',
  },
  Code: {
    textColor: '#171717',
    fontSize: '13px',
    fontFamily: '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, Monaco, monospace',
  },
  Alert: {
    borderRadius: '8px',
    colorSuccess: '#fafafa',
    borderSuccess: '1px solid #ebebeb',
    colorWarning: '#ffefcf',
    borderWarning: '1px solid #ffefcf',
    colorError: '#f7d4d6',
    borderError: '1px solid #f7d4d6',
    colorInfo: '#fafafa',
    borderInfo: '1px solid #ebebeb',
    iconColorSuccess: '#0070f3',
    iconColorInfo: '#0070f3',
    titleTextColorWarning: '#ab570a',
  },
  List: {
    color: '#ffffff',
    borderColor: '#ebebeb',
    borderRadius: '8px',
  },
  Collapse: {
    titleFontWeight: '500',
    titleTextColor: '#171717',
    dividerColor: '#ebebeb',
    borderRadius: '8px',
    borderColor: '#ebebeb',
  },
  Descriptions: {
    thColor: '#fafafa',
    tdColor: '#ffffff',
    thTextColor: '#888888',
    tdTextColor: '#171717',
    borderColor: '#ebebeb',
    borderRadius: '8px',
    thFontWeight: '400',
    thFontSize: '12px',
    tdFontSize: '14px',
  },
  Result: {
    titleTextColor: '#171717',
    textColor: '#4d4d4d',
    iconColorSuccess: '#0070f3',
    iconColorInfo: '#171717',
  },
  Dialog: {
    color: '#ffffff',
    borderRadius: '12px',
    titleTextColor: '#171717',
    textColor: '#4d4d4d',
  },
  Modal: {
    color: '#ffffff',
    borderRadius: '12px',
  },
}